### ISSUE TITLE
Monte Carlo Dropout code not found

### ISSUE THREAD

**Issue by tejasri19** [senecal-jjs/intel_spectrumnet#1]
@senecal-jjs Pls provide code how you integrated Monte carlo drop out code in the network architecture.

**Comment by senecal-jjs** [comment]
@tejasri19 see here https://github.com/senecal-jjs/intel_spectrumnet/blob/05331eb162ed6c9290ad71e72e0f16a1a21ff60c/SpectrumNet/spectrumnet.py#L89

**Comment by tejasri19** [comment]
> @tejasri19 see here
> 
> https://github.com/senecal-jjs/intel_spectrumnet/blob/05331eb162ed6c9290ad71e72e0f16a1a21ff60c/SpectrumNet/spectrumnet.py#L89

But its not MC - dropout right? How do you calculate uncertainty using this?

**Comment by senecal-jjs** [comment]
Here's the original paper describing the technique, https://arxiv.org/abs/1506.02142

By making multiple passes through the network for a single input, with different neurons being randomly switched off on each pass, you are effectively sampling a probability distribution. 

Here's a relevant comment from the original paper I linked. 

```
Note that the dropout NN model itself is not changed.
To estimate the predictive mean and predictive uncertainty
we simply collect the results of stochastic forward passes
through the model
```

**Comment by tejasri19** [comment]
> Here's the original paper describing the technique, https://arxiv.org/abs/1506.02142
> 
> By making multiple passes through the network for a single input, with different neurons being randomly switched off on each pass, you are effectively sampling a probability distribution.
> 
> Here's a relevant comment from the original paper I linked.
> 
> ```
> Note that the dropout NN model itself is not changed.
> To estimate the predictive mean and predictive uncertainty
> we simply collect the results of stochastic forward passes
> through the model
> ```

Do you say dropout is different from MC dropout ?
